---
development:
  CLOUDAINRY_CLOUD: thypowerhouse
  API_KEY: '613239317455218'
  API_SECRET: S5DF4bk0mGBtB8WYXT4izLeNqUg
  ENHANCE_IMAGE_TAG: true
  STATIC_IMAGE_SUPPORT: false
production:
  CLOUDAINRY_CLOUD: thypowerhouse
  API_KEY: '613239317455218'
  API_SECRET: S5DF4bk0mGBtB8WYXT4izLeNqUg
  ENHANCE_IMAGE_TAG: true
  STATIC_IMAGE_SUPPORT: false
test:
  CLOUDAINRY_CLOUD: thypowerhouse
  API_KEY: '613239317455218'
  API_SECRET: S5DF4bk0mGBtB8WYXT4izLeNqUg
  ENHANCE_IMAGE_TAG: true
  STATIC_IMAGE_SUPPORT: false
